fix: add check if envsubst download success, else exit workflow

diff --git a/.github/workflows/openapi_build.yml b/.github/workflows/openapi_build.yml
--- a/.github/workflows/openapi_build.yml
+++ b/.github/workflows/openapi_build.yml
@@ -37,6 +37,10 @@ jobs:
             # Get a8m/envsubst (required for default vals syntax ${VAR:-default})
             echo "Downloading envsubst"
             curl -L https://github.com/a8m/envsubst/releases/download/v1.2.0/envsubst-`uname -s`-`uname -m` -o envsubst
+            if [ $? -ne 0 ]; then
+                echo "Failed to download envsubst"
+                exit 1
+            fi
             chmod +x envsubst
             echo "Substituting variables from ${EXAMPLE_DOTENV} --> .env"
             ./envsubst < "${EXAMPLE_DOTENV}" > .env
